# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 09:05
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=django_markdown.models.MarkdownField(default='SOME STRING'),
        ),
    ]
