# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 09:13
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161111_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=100, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
